# Generated by Django 6.0.5 on 2026-05-28 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_created_at_venue_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Amenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="venue",
            name="amenities",
            field=models.ManyToManyField(
                blank=True, related_name="venues", to="accounts.amenity"
            ),
        ),
    ]
