# Generated by Django 6.0.5 on 2026-06-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_amenity_venue_amenities"),
    ]

    operations = [
        migrations.AddField(
            model_name="venue",
            name="rejection_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
