# Generated by Django 6.0.5 on 2026-06-02 09:39

from django.db import migrations
from django.contrib.postgres.operations import BtreeGistExtension

class Migration(migrations.Migration):

    dependencies = []

    operations = [
        BtreeGistExtension(),
    ]
