# Generated by Django 6.0.5 on 2026-06-02 09:40

import django.contrib.postgres.constraints
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0004_venue_rejection_reason"),
        ("bookings", "0001_enable_btree_gist"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        help_text="Must be top-of-the-hour (e.g., 14:00:00)"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        help_text="Must be top-of-the-hour (e.g., 16:00:00)"
                    ),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="venue_bookings",
                        to="accounts.venue",
                    ),
                ),
            ],
            options={
                "constraints": [
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(("status__in", ["pending", "confirmed"])),
                        expressions=[
                            ("venue", "="),
                            (
                                models.Func(
                                    "start_time",
                                    "end_time",
                                    models.Value("[)"),
                                    function="tstzrange",
                                    output_field=models.Field(),
                                ),
                                "&&",
                            ),
                        ],
                        name="prevent_overlapping_bookings",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_time__gt", models.F("start_time"))),
                        name="end_after_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("total_price__gte", 0)),
                        name="non_negative_total_price",
                    ),
                ],
            },
        ),
    ]
